# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Buty.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1575, 796)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1568, 778))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.img_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.img_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Buty_frames/Leonardo_DiCaprio_1/GG0000_0.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.img_1.setIcon(icon)
        self.img_1.setIconSize(QtCore.QSize(768, 768))
        self.img_1.setObjectName("img_1")
        self.horizontalLayout.addWidget(self.img_1)
        self.img_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.img_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Buty_frames/Leonardo_DiCaprio_2/GG0042_0.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.img_2.setIcon(icon1)
        self.img_2.setIconSize(QtCore.QSize(768, 768))
        self.img_2.setObjectName("img_2")
        self.horizontalLayout.addWidget(self.img_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
